# https://github.com/marketplace/actions/toc-generator

on: push

name: Generate markdown

#permissions:
#  contents: write

jobs:

  generate_template:
    name: Generate markdown from template
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - run: |
          pip install -r requirements.txt
          sudo apt-get install -y make git

      - run: |
          env
          make

#      - name: Commit and push changes
#        uses: devops-infra/action-commit-push@v0.9.2
#        with:
#          github_token: ${{ secrets.ACCESS_TOKEN }}
#          commit_message: Update changed makefiles from template

      - env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          INPUT_ORGANIZATION_DOMAIN: github.com
        run: |
          set -x
          env

          git config --global safe.directory "${GITHUB_WORKSPACE}"
          git config --global safe.directory /github/workspace
          git remote set-url origin "https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@${INPUT_ORGANIZATION_DOMAIN}/${GITHUB_REPOSITORY}"
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.${INPUT_ORGANIZATION_DOMAIN}"

          if [ -n "$(git diff)" ] ; then
            find . -type f -iname '*.md' -print0 | \
              xargs -0 ./.bin/git-commit-file.sh
          fi

