# https://github.com/marketplace/actions/toc-generator

on: push

name: Generate markdown

#permissions:
#  contents: write

jobs:

  generate_template:
    name: Generate markdown from template
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - run: |
          pip install -r requirements.txt
          sudo apt-get install -y make git

      - run: |
          make

      - name: Commit and push changes
        uses: devops-infra/action-commit-push@v0.9.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit_message: Update changed makefiles from template

#      - with:
#          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
#        run: |
#          if [ -n "$(git diff)" ] ; then
#            find . -type f -iname '*.md' -print0 | \
#              xargs -0 ./.bin/git-commit-file.sh
#          fi

